### ISSUE TITLE
Misspelt macOS bundle identifier com.apple.Termial

### ISSUE THREAD

**Issue by teor2345** [autonomys/space-acres#300]
When I launch `space-acres` 0.1.35 (3be41b0) from Terminal.app on macOS, I get the following error:
> 2024-09-05T01:06:49.024967Z ERROR space_acres::frontend: Failed to set application bundle identifier error=Could not set application 'xyz.autonomys.space-acres', using default "com.apple.Termial"

The correct spelling is `com.apple.Terminal`.

This misspelling appears to be from a dependency, I can't find it in this repository using GitHub search. I'm also not sure if this bug has any practical impact.

**Comment by nazar-pc** [comment]
Does it crash or just logs an error?

The Terminal thing is irrelevant, the issue is that OS doesn't recognize `xyz.autonomys.space-acres` for notification purposes. I have not invested much time into macOS, but I did try to set things up in a way that would plausibly enable desktop notifications. Apparently the OS didn't accept identifier, `notify-rust` library had a fallback and that fallback had a typo in it too :upside_down_face: 

Feel free to investigate and fix, but I don't think it is worth my time honestly.

**Comment by teor2345** [comment]
> Does it crash or just logs an error?

It just logs an error.

> The Terminal thing is irrelevant, the issue is that OS doesn't recognize `xyz.autonomys.space-acres` for notification purposes. I have not invested much time into macOS, but I did try to set things up in a way that would plausibly enable desktop notifications. Apparently the OS didn't accept identifier, `notify-rust` library had a fallback and that fallback had a typo in it too 🙃
> 
> Feel free to investigate and fix, but I don't think it is worth my time honestly.

I think this happens because I’m running the binary without building the application directory (also called a bundle).

The underlying system API expects a bundle to exist:
https://github.com/h4llow3En/mac-notification-sys/blob/d6c108cc6ca9ca13092e6cefe39df62f91149a0e/objc/notify.m#L18
https://developer.apple.com/documentation/coreservices/1449290-lscopyapplicationurlsforbundleid

**Comment by nazar-pc** [comment]
That makes a lot of sense, also turns out the typo is just in the error message, the actual code uses the correct one, so you should still be able to see notifications in some form: https://github.com/h4llow3En/mac-notification-sys/blob/d6c108cc6ca9ca13092e6cefe39df62f91149a0e/src/error.rs#L29
